# 测试环境配置文件
server:
  port: 9090
# 日志持久化，设置日志保存路径（绝对路径）
# path 默认文件名为spring.log
# name 可以具体设置日志保存文件名
# 日志是追加写的，日志一旦产生就会永久保存
# spring boot默认日志文件大小为 10MB 超过10MB就会创建新的日志文件
logging:
  file:
    name: E:\javaCode\log\log_all.log