server:
  port: 63110
  servlet:
    context-path: /system
#微服务配置
spring:
  application:
    name: system-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.101.128:3306/xc_system?serverTimezone=UTC&userUnicode=true&useSSL=false&
    username: root
    password: wuhao1126

# 日志文件配置路径
logging:
  config: classpath:log4j2-dev.xml

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 实体类的别名扫描包
  type-aliases-package: com/xuecheng/system/model/po
  # 配置全局id为自增
  global-config:
    db-config:
      id-type: auto
  #      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
  #      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
  #      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  # 配置枚举处理器
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler

# swagger 文档配置
swagger:
  title: "学成在线系统管理"
  description: "系统管理接口"
  base-package: com.xuecheng.system
  enabled: true
  version: 1.0.0
