server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/cloud_order?useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: order-server # 配置服务名称
  cloud:
    nacos:
      server-addr: nacos:8848 # 添加nacos地址
      discovery:
        cluster-name: HZ # 配置集群名称
#        namespace: ec69ff24-f1c8-4416-9835-856eb7e81ee3

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:
#      defaultZone:  http://127.0.0.1:9990/eureka # 配置eureka地址
user-server: # 给某个微服务配置负载均衡规则，这里是user-server服务
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则
ribbon:
  eager-load:
    enabled: false
    clients:
      - user-server # 争对服务配置饥饿加载



# 配置feign日志级别
# NONE：不记录任何信息，默认日志级别
# BASIC：仅记录请求的方法，URL，以及相应状态吗3和相应时间
# HEADERS：在BASIC基础上，额外记录请求和响应头信息
# FULL：记录请求和响应明细，包括请求头，请求体，元数据
# 注意：建议使用 NONE BASIC，服务器记录日志信息也需要消耗一定的资源

# feign优化：使用具有连接池的客户端
#  URLConnection：默认实现，不支持连接池
#  Apache HttpClient：支持连接池
#  OKHttp：支持连接池
feign:
  client:
    config:
      default:  # 争对所有微服务都生效。如果写某个具体微服务信息，就只争对这个微服务生效
        logger-level: FULL
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数




