logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
# 配置远程mq
spring:
  rabbitmq:
    host: 192.168.29.130 # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: wuhao # 用户名
    password: 123 # 密码