spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wuhao1126
logging:
  level:
    com.itheima: debug
  pattern:
    dateformat: HH:mm:ss
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 实体类的别名扫描包
  type-aliases-package: com.itheima.mp.domain.po
  # 配置全局id为自增
  global-config:
    db-config:
      id-type: auto
# swagger配置
knife4j:
  enable: true
  openapi:
    title: 用户管理接口文档
    description: "用户管理接口文档"
    email: 2945608334@qq.com
    concat: 吴浩
    url:
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.itheima.mp.controller